# Generated by Django 5.1.2 on 2024-10-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.ImageField(upload_to='capas/')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('submetido', 'Submetido'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='em_andamento', max_length=20)),
                ('autores', models.ManyToManyField(limit_choices_to={'status': 'ativo'}, to='app_tcc.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tcc.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tcc.orientador')),
            ],
        ),
    ]
